version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - "4000:3000"
      - "5555:5555"
    networks:
      - app-network
    
  
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: nestjs-demo-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - app-network  # 追加

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nestjs-demo-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - 8000:80
    networks:
      - app-network  # 追加

networks:
  app-network:
    driver: bridge
